### ISSUE TITLE
local gradio demo has a bug

### ISSUE THREAD

**Issue by wbbeyourself** [aiwaves-cn/RecurrentGPT#1]
File "xxx/RecurrentGPT/gradio_server.py", line 65, in init
    init_paragraphs = get_init(chatbot, init_prompt(novel_type, description))
  File "xxx/RecurrentGPT/utils.py", line 38, in get_init
    with open(init_text,'r',encoding='utf-8') as f:
TypeError: expected str, bytes or os.PathLike object, not Chatbot

I guess this demo use web session for GPT4.
How about call gpt-3.5-turbo api for the demo ? 
Thank you for your interesting work.

**Comment by swaggy-TN** [comment]
Hi Bing,
Thank you for your attention. We currently update the weblink towards our online demo. We highly encourage you to visit the demo and provide us with your valuable feedback.

**Comment by MichaelZhouwang** [comment]
Hey we have uploaded a new version for local gradio. We're using GPT-3.5-Turbo for our web demo instead of GPT-4 (since GPT-4 is really slow :))
