### ISSUE TITLE
Unable to continue, an error will be reported

### ISSUE THREAD

**Issue by femnn** [aiwaves-cn/RecurrentGPT#10]
![cmd_wU0DCMOkxb](https://github.com/aiwaves-cn/RecurrentGPT/assets/28421346/1ea4f55b-b0c0-4cd6-b7cc-0f3b4fa7dd69)

**Comment by tractorjuice** [comment]
I've seen this error, I just copied the code for 'step' and made a 'step_with_edit' version. It seems to work, but not sure if there is something missing.

**Comment by swaggy-TN** [comment]
Thanks for your attention!
We've fixed the bug in gradio_server.py. Please try now😊

**Comment by swaggy-TN** [comment]
NB: still unstable when using a proxy to call OpenAI API. There could occur some cookies key errors.
