### ISSUE TITLE
No Chinese version

### ISSUE THREAD

**Issue by LI-GUOJIE** [aiwaves-cn/RecurrentGPT#12]
I see "第一人称互动式小说生成器" while opening the DEMO website (https://www.aiwaves.org/interactivefiction)
But it disappears while I run it on Hugging Face (https://imliguojie-recurrent.hf.space)

Could you put it as an option in the configuration file?

**Comment by MichaelZhouwang** [comment]
Hi. We have not released the code for interactive fiction. We're working on an improved version of it and plan to release it soon!

**Comment by vtxyer** [comment]
We greatly appreciate the improved version and eagerly anticipate your next release. Thank you for providing us with this exceptional model. !!!

**Comment by LI-GUOJIE** [comment]
> 

Thank you for the amazing project. I look forward to the improved version :)
