### ISSUE TITLE
fine tune

### ISSUE THREAD

**Issue by Bellafc** [aiwaves-cn/RecurrentGPT#15]
How can we fine-tune this recurrent gpt model so that it can output some other type of information but not only the novels?

**Comment by MichaelZhouwang** [comment]
Hey you can simply do some prompt engineering in recurrentgpt.py to make it generate other kinds of information. You can not fine-tune the parameters of the model because it is based on OpenAI's GPT-3.5-turbo model which are not open-sourced.
