### ISSUE TITLE
I'm getting an issue with the 'cookie'

### ISSUE THREAD

**Issue by TheSeanLavery** [aiwaves-cn/RecurrentGPT#4]
Trying to run this locally.

I got the cookie issue, and I tried editing the python file to skip the cookie if it wasn't there for the first time. I was able to generate the text one time, but after clicking next I get another cookie error.

I think this is something wrong with my local setup, or is this the project?

**Comment by MichaelZhouwang** [comment]
Hey thanks for your interest! Maybe you can try our new web demo code? If it still does not work, can you please share us the error info?
