### ISSUE TITLE
How can I use it locally?

### ISSUE THREAD

**Issue by DerickYau** [aiwaves-cn/RecurrentGPT#5]
This is an exciting extension of ChatGPT. 
Can you write a detailed teaching for local use? 
Thank.

**Comment by MichaelZhouwang** [comment]
Hey thanks for your interest! To use it locally, you can set up a gradio demo locally by:
```
export OPENAI_API_KEY="your_api_key"
python gradio_server.py

```

otherwise you can also modify main.py and run the following command 
`sh recurrent.sh`
